### ISSUE TITLE
Port micropython into Atari ST(e)

### ISSUE THREAD

**Issue by sporniket** [sporniket/ideas#12]
# Phase 0

* [ ] setup toolchain (gcc)
* [ ] Initial port : minimal + REPL, using the console (cconin, cconout)

# Phase 1
* [ ] profile "Kernel TOS" (kerneltosapp) : unrestricted access to bios/xbios/gemdos and hardware registers (each chip has a module, work as superuser)
* [ ] profile "TOS" (tosapp) : only access to bios/xbios/gemdos, and allowed user RAM
* [ ] MIPYBM.TOS : "MIcroPYthon Bare Metal" environnement "Kernel TOS" pour développer des applications exclusives (démarrage sur disquette dans un dossier auto)

# Phase 2
* [ ] profile "GEM" (gemapp) : only access to vdi/aes, and high level file system
* [ ] profile "ACC" (gemacc) : like gemapp, with specifics for writing GEM accessories
* [ ] MIPYCON.ACC : "MIcro PYthon CONsole", GEM accessory embedding a micropython REPL. Can invoke python scripts, edit one single script at a time.

# Phase 3
* [ ] MIPYIDE.PRG : "MIcro PYthon IDE" ; workspace, source editor, launcher ; package/compile

# Technical points

* How to distribute a set of script as an application :
  * a runtime like GFA (file selector, and run the selected script) ?
  * provide a runner with data files around (like a runtime, without file selector) ?
  * provide a "pyc" bundle embedded into a base app (python runtime without REPL) ?

> The solution that looks the most like a regular program is preferred
